# Makefile.in generated by automake 1.11 from Makefile.am.
# src/ruby/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



pkgdatadir = $(datadir)/MonetDB-client
pkgincludedir = $(includedir)/MonetDB-client
pkglibdir = $(libdir)/MonetDB-client
pkglibexecdir = $(libexecdir)/MonetDB-client
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin9.7.0
host_triplet = i386-apple-darwin9.7.0
target_triplet = i386-apple-darwin9.7.0
subdir = src/ruby
DIST_COMMON = README $(srcdir)/Makefile.am $(srcdir)/Makefile.in TODO
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/clients_config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
depcomp =
am__depfiles_maybe =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
ACLOCAL = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run aclocal-1.11
AMTAR = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run tar
AR = ar
AS = as
AUTOCONF = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run automake-1.11
AWK = awk
BASH = /bin/sh
BUILDTOOLS_CONFDIR = 
BUILDTOOLS_CONFIG = 
BZ_CFLAGS = 
BZ_LIBS =  -lbz2
CC = gcc
CCDEPMODE = depmode=none
CFLAGS = -O2 $(X_CFLAGS)
CFLAGS_NO_OPT = -O0
CLIENTS_BUILD = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
CLIENTS_SOURCE = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
CONFIG_H = clients_config.h
CPP = gcc -E
CPPFLAGS =  -std=c99
CURL_CFLAGS = 
CURL_CONFIG = 
CURL_LIBS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=none
CXXFLAGS = -g -O2
CYGPATH_W = echo
CYGPATH_WP = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DIRSEP = /
DLLTOOL = dlltool
DL_LIBS = -ldl
DSYMUTIL = dsymutil
DVIPS = dvips
ECHO = /bin/echo
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = 
FFLAGS = 
FIG2DEV = 
FIG2DEV_EPS = eps
GCC_BISON_CFLAGS = 
GCC_SWIG_CFLAGS = 
GREP = /usr/bin/grep
HWCOUNTERS_INCS = 
HWCOUNTERS_LIBS = 
ICC_BISONFLAGS = 
ICC_BISON_CFLAGS = 
ICC_SWIG_CFLAGS = 
ICONV_CFLAGS = 
ICONV_LIBS =  -liconv
INSTALL = /usr/bin/install -c
INSTALL_BACKUP = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LATEX = latex
LATEX2HTML = 
LDFLAGS = 
LEX = 
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LINUX_DIST = 
LN_S = ln -s
LOCKFILE = lockfile -r 2
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/missing --run makeinfo
MALLOC_LIBS = 
MATH_LIBS = -lm
MEL_LIBS = 
MKDIR_P = ../../conf/install-sh -c -d
MONETDB_CONFDIR = /usr/local/share/MonetDB/conf
MONETDB_CONFIG = /usr/local/bin/monetdb-config
MONETDB_INCLUDEDIR = /usr/local/include/MonetDB
MONETDB_INCS = -I${MONETDB_INCLUDEDIR} -I${MONETDB_INCLUDEDIR}/common -I${MONETDB_INCLUDEDIR}/gdk
MONETDB_LIBS = -L/usr/local/lib
MONETDB_PREFIX = /usr/local
MONETDB_VERSION = 1.32.4
MV = mv -f
MX = 
NMEDIT = nmedit
NO_INLINE_CFLAGS = 
NO_OPTIMIZE_FILES = 
NO_X_CFLAGS = _NO_X_CFLAGS_
OBJC = 
OBJDUMP = objdump
OBJEXT = o
ODBC_INCS = 
ODBC_LIBS = 
OPENSSL_INCS = 
OPENSSL_LIBS = 
PACKAGE = MonetDB-client
PACKAGE_BUGREPORT = monet@cwi.nl
PACKAGE_NAME = MonetDB clients
PACKAGE_STRING = MonetDB clients 1.32.4
PACKAGE_TARNAME = MonetDB-client
PACKAGE_VERSION = 1.32.4
PATHSEP = :
PATH_SEPARATOR = :
PCL_CFLAGS = 
PCL_LIBS = 
PCRETEST = 
PCRE_CFLAGS = 
PCRE_CONFIG = 
PCRE_LIBS = 
PDFLATEX = pdflatex
PERL = /opt/local/bin/perl
PERL_INCS = -I/opt/local/lib/perl5/5.8.9/darwin-2level/CORE
PERL_LIBDIR = lib/perl5/vendor_perl/5.8.9/darwin-2level
PERL_LIBS = -L/opt/local/lib/perl5/5.8.9/darwin-2level/CORE -lperl
PHP_CONFIG = /usr/bin/php-config
PHP_EXTENSIONDIR = lib/php/extensions/no-debug-non-zts-20060613
PHP_INCS =  -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
PTHREAD_INCS =  
PTHREAD_LIBS =  -lpthread
PYTHON = /usr/bin/python
PYTHON_LIBDIR = lib/python2.5/site-packages
QCLIENTS_BUILD = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
QCLIENTS_SOURCE = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
QDIRSEP = /
QXCLIENTS_BUILD = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
QXCLIENTS_SOURCE = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
QXbindir = ${exec_prefix}/bin
QXdatadir = ${prefix}/share
QXdatarootdir = ${prefix}/share
QXexec_prefix = ${prefix}
QXincludedir = ${prefix}/include
QXinfodir = ${datarootdir}/info
QXlibdir = ${exec_prefix}/lib
QXlibexecdir = ${exec_prefix}/libexec
QXlocalstatedir = ${prefix}/var
QXmandir = ${datarootdir}/man
QXprefix = /usr/local
QXsrcdir = .
QXsysconfdir = ${prefix}/etc
Qbindir = ${exec_prefix}/bin
Qdatadir = ${prefix}/share
Qdatarootdir = ${prefix}/share
Qexec_prefix = ${prefix}
Qincludedir = ${prefix}/include
Qinfodir = ${datarootdir}/info
Qlibdir = ${exec_prefix}/lib
Qlibexecdir = ${exec_prefix}/libexec
Qlocalstatedir = ${prefix}/var
Qmandir = ${datarootdir}/man
Qprefix = /usr/local
Qsrcdir = .
Qsysconfdir = ${prefix}/etc
RANLIB = ranlib
READLINE_INCS = 
READLINE_LIBS = 
READLINK = echo
RM = rm -f
RPMBUILD = 
RUBY = /usr/bin/ruby
RUBYGEM = /usr/bin/gem
RUBY_DIR = /Library/Ruby/Gems/1.8
SED = /usr/bin/sed
SET_MAKE = 
SHARED_LIBS = 
SHELL = /bin/sh
SOCKET_LIBS = 
SOEXT = .dylib
STRIP = strip
SUN_NOERR_CFLAGS = 
SUN_NOOPT_CFLAGS = 
SWIG = 
TEXI2HTML = texi2html
THREAD_SAVE_FLAGS = $(thread_safe_flag_spec) -D_REENTRANT
UNIXODBC_CONFIG = 
VERSION = 1.32.4
XCLIENTS_BUILD = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
XCLIENTS_SOURCE = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
XPHP_EXTENSIONDIR = lib/php/extensions/no-debug-non-zts-20060613
X_CFLAGS = 
Xbindir = ${exec_prefix}/bin
Xdatadir = ${prefix}/share
Xdatarootdir = ${prefix}/share
Xexec_prefix = ${prefix}
Xincludedir = ${prefix}/include
Xinfodir = ${datarootdir}/info
Xlibdir = ${exec_prefix}/lib
Xlibexecdir = ${exec_prefix}/libexec
Xlocalstatedir = ${prefix}/var
Xmandir = ${datarootdir}/man
Xprefix = /usr/local
Xsrcdir = .
Xsysconfdir = ${prefix}/etc
YACC = 
YFLAGS = 
Z_CFLAGS = 
Z_LIBS =  -lz
abs_builddir = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/src/ruby
abs_srcdir = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/src/ruby
abs_top_builddir = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
abs_top_srcdir = /Users/tincoandringa/Downloads/MonetDB-client-1.32.4
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chf - "$$tardir"
am__untar = ${AMTAR} xf -
anttranslatepath = echo
bindir = ${exec_prefix}/bin
bits = 32
build = i386-apple-darwin9.7.0
build_alias = 
build_cpu = i386
build_os = darwin9.7.0
build_vendor = apple
builddir = .
datadir = ${prefix}/share
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin9.7.0
host_alias = 
host_cpu = i386
host_os = darwin9.7.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/tincoandringa/Downloads/MonetDB-client-1.32.4/conf/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/conf/install-sh -c -d
oids = 32
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = i386-apple-darwin9.7.0
target_alias = 
target_cpu = i386
target_os = darwin9.7.0
target_vendor = apple
thread_safe_flag_spec = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
translatepath = echo
AUTOMAKE_OPTIONS = no-dependencies 1.4 foreign
#NEED_MX = 1
SUBDIRS = adapter
INCLUDES = -I$(srcdir)
BUILT_SOURCES = 
MOSTLYCLEANFILES = 
EXTRA_DIST = Makefile.msc Changelog README TODO ruby-monetdb-sql-0.1.gemspec  $(BUILT_SOURCES)
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/ruby/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/ruby/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-recursive
all-am: Makefile all-local
installdirs: installdirs-recursive
installdirs-am:
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-exec-local

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-local

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) all check \
	ctags-recursive install install-am install-strip \
	tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am all-local check check-am clean clean-generic \
	clean-libtool ctags ctags-recursive dist-hook distclean \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-exec-local install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
	ps ps-am tags tags-recursive uninstall uninstall-am \
	uninstall-local

dist-hook:
	mkdir -p $(distdir)/examples
	cp -pR $(srcdir)/examples/* $(distdir)/examples
	find $(distdir)/examples -depth -name CVS -exec rm -rf {} \;
	find $(distdir)/examples -perm -0100 -type f ! -name \*.bat ! -name \*.sh ! -exec grep -q '^#!' {} \; -exec chmod a-x {} \;
	mkdir -p $(distdir)/lib
	cp -pR $(srcdir)/lib/* $(distdir)/lib
	find $(distdir)/lib -depth -name CVS -exec rm -rf {} \;
	find $(distdir)/lib -perm -0100 -type f ! -name \*.bat ! -name \*.sh ! -exec grep -q '^#!' {} \; -exec chmod a-x {} \;
all-local-gem_monetdb: ruby-monetdb-sql-0.1.gem
ruby-monetdb-sql-0.1.gem: ruby-monetdb-sql-0.1.gemspec
	d=$(dir $<); [ "$$d" -ef . ] || (cd "$$d"; tar cf - ruby-monetdb-sql-0.1.gemspec `sed -n '/.*\.files *= *\[ */{s///;s/ *\].*//;s/"//g;s/ *, */ /g;p;}' "ruby-monetdb-sql-0.1.gemspec"`) | tar xf -
	gem build ruby-monetdb-sql-0.1.gemspec
install-exec-local-ruby-monetdb-sql-0_1_gemspec: ruby-monetdb-sql-0.1.gem
	mkdir -p $(DESTDIR)$(prefix)/$(RUBY_DIR)
	gem install --local --install-dir $(DESTDIR)$(prefix)/$(RUBY_DIR) --force --rdoc ruby-monetdb-sql-0.1.gem
uninstall-exec-local-ruby-monetdb-sql-0_1_gemspec: ruby-monetdb-sql-0.1.gem
	gem uninstall --install-dir $(DESTDIR)$(prefix)/$(RUBY_DIR) ruby-monetdb-sql-0.1.gem
#install-exec-local-ruby-monetdb-sql-0_1_gemspec:
#uninstall-exec-local-ruby-monetdb-sql-0_1_gemspec:
uninstall-local: uninstall-local-ruby-monetdb-sql-0_1_gemspec
install-exec-local: install-exec-local-ruby-monetdb-sql-0_1_gemspec
all-local: all-local-gem_monetdb

#  include $(BUILDTOOLS_CONFDIR)/rules.mk
#  include $(top_builddir)/extra.mk

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
